server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin


#test: 2
#  application:
#    name: consul-service
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery: # 服务发现配置
#        enabled: true
#        register: true
#        deregister: true
#        prefer-ip-address: true
#        health-check-interval: 10s
#        health-check-critical-timeout: 30s
#        health-check-path: /health
#        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} # 应用名称+服务器IP+端口
#      config:
#          prefix: config
#          enabled: true
#          format: YAML
#          data-key: user
#


#spring.cloud.consul.config.host=localhost
#spring.cloud.consul.port=8500
#spring.cloud.consul.discovery.enabled=true
#spring.cloud.consul.discovery.register=true
#spring.cloud.consul.discovery.prefer-ip-address=true
#spring.cloud.consul.discovery.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#



##
##redis配置开始
## Redis数据库索引（默认为0）
#spring.redis.database=0
## Redis服务器地址
#spring.redis.host=localhost
## Redis服务器连接端口
#spring.redis.port=6379
## Redis服务器连接密码（默认为空）
##spring.redis.password=123456
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.jedis.pool.max-active=1024
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.jedis.pool.max-wait=10000
## 连接池中的最大空闲连接
#spring.redis.jedis.pool.max-idle=200
## 连接池中的最小空闲连接
#spring.redis.jedis.pool.min-idle=0
## 连接超时时间（毫秒）
#spring.redis.timeout=0
##redis配置结束
#spring.redis.block-when-exhausted=true

